const List<String> parauapebasNeighborhoods = [
  'Cidade Nova',
  'Primavera',
  'Maranhão',
  'Rio Verde',
  'Nova Vida',
  'União',
  'Liberdade I',
  'Liberdade II',
  'Da Paz',
  'Caetanópolis',
  'Guanabara',
  'Paraíso',
  'Esplanada',
  'Linha Verde',
  'Beira Rio',
  'Parque dos Carajás',
  'Vila Rica',
  'Habitar Feliz',
  'Altamira',
  'Novo Horizonte',
  'Jardim Canadá',
  'Betânia',
  'Alto Bonito',
  'FAP',
  'Santa Luzia',
  'Novo Viver',
  'Vale do Sol',
  'Tropical',
  'Polo Moveleiro',
  'Minérios',
  'Cidade Jardim',
  'Parque das Nações',
  'São Lucas',
  'Brasília',
  'Morada Nova',
  'Jardim América',
  'Jardim Planalto',
  'Nova Carajás',
  'Apoena',
  'Amazônia',
  'Alvorá',
  'Novo Brasil',
];
